name:                interval
version:             0.0.0
github:              "AliceRixte/interval"
license:             BSD3
author:              "Alice Rixte"
maintainer:          "alice.rixte@u-bordeaux.fr"
copyright:           "BSD3"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Real interval with closed or open bounds.
category:            numeric
description:         Please see the README on GitHub at <https://github.com/AliceRixte/interval/blob/main/README.md>

dependencies:
- base >= 4.14 && < 5
- ieee754

ghc-options:
  - -Wall

tested-with: GHC == 9.8.4

library:
  ghc-options:
  - -O2
  source-dirs: src

